name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: "auto"
        required: false
        description: "Used to manually set the version"

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@dc2fa1d2d14e165327e0e58bd1287ca2658fc64e # 2.0.21
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN}}
